### ISSUE TITLE
Change baseUrl to not use $_SERVER variables anymore

### ISSUE THREAD

**Issue by janhenckens** [statikbe/craft#11]

**Comment by janhenckens** [comment]
Also add `baseUrl` variable to icon paths and webpack templates.

**Comment by carolineboeykens** [comment]
Hey Jan, kan je even toelichten waarom dit net nodig is?

Momenteel staat er nog dit:

`'baseUrl' => strtolower((isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off' ? 'https://' : 'http://') . $_SERVER['SERVER_NAME']),`

Heb jij een voorstel hoe we dit anders kunnen aanpakken?

**Comment by janhenckens** [comment]
Ik zou dit vervangen door een vaste url, of iets wat uit de `.env` file komt. 

`$_SERVER` gaat soms issues geven als je via command line bepaalde dingen gaat doen, omdat die requests niet via Apache gaan en dan is er dus gaan `$_SERVER`
