### ISSUE TITLE
Add "Video description" field to both video blocks

### ISSUE THREAD

**Issue by janhenckens** [statikbe/craft#125]

**Comment by KarelJanVanHaute** [comment]
@janhenckens What was the idea here? To add description as an extra field in the backend?
And where do we want to show it in the frontend. Beneath the video?

**Comment by KarelJanVanHaute** [comment]
And also add the option to add a placeholder image.

**Comment by janhenckens** [comment]
Correct, sort of an "alt text" for video - possibly with the option to link to a page to describe what's in the video?

**Comment by KarelJanVanHaute** [comment]
For the video placeholder see porject INTDIG. Commit CB: Video Placeholder (anuary 24th, 2024 10:43 AM)
