### ISSUE TITLE
Seperate (or differentiate between) asset "Caption" and asset "Alt text" fields?

### ISSUE THREAD

**Issue by AntonLecock** [statikbe/craft#173]
Captions sometimes are used for visible text below the image, while at the same time, they are generally also used as alt-text in the template. 
The function of a caption and an alt-text is not always the same. 
Should we add a primary description field for alt-text (most important), and clarify that the second field (caption) is used to display text (generally) below the image? Or are there any other solutions?

**Comment by Numkil** [comment]
Alle velden op een asset meer uitleg geven. Alle templates aanpassen om die velden correct te gaan toepassen.
