### ISSUE TITLE
Change the default ddev config so the urls are always in our correct format.

### ISSUE THREAD

**Issue by KarelJanVanHaute** [statikbe/craft#203]
Add this to the config
``project_tld: local.statik.be``
And leave the dns change settings empty like so.
```
additional_hostnames: []
additional_fqdns: []
```
This will offer the correct url to our local setup format. And this will set the two variables ``CRAFT_WEB_URL`` and ``PRIMARY_SITE_URL`` in the environement file to those correct urls. So no more ddev.site issues.

**Comment by janhenckens** [comment]
Can be added to https://github.com/statikbe/craft/pull/208 I think?
