### ISSUE TITLE
--ignore-optional flag in yarn install does not work

### ISSUE THREAD

**Issue by carolineboeykens** [statikbe/craft#228]
When we run `yarn install --ignore-optional && yarn prod` the build fails

**Comment by KarelJanVanHaute** [comment]
For now, we're going to leave the option out. The optional dependencies are not causing any trouble building on the server. So there is no need for this is anymore. 

What is happening?
For as far as I can figure it out. For some reason, @rollup is defined as an optional dependency. But you do need it for the build. So if you run it with the option --ignore-optional, this gets also skipped. And then the build fails. 

So for now no further action is needed I guess.
