### ISSUE TITLE
Optimize Formie Stencil

### ISSUE THREAD

**Issue by HannahDeWachter** [statikbe/craft#241]
- Add privacy checkbox
- Change "Submission Title Format" to: "Email"-"timestamp"
- Change Data Retention to (for example) 2 years
- Translate Field labels to NL

**Comment by HannahDeWachter** [comment]
By adding the privacy checkbox I discovered this is not being styled.
<img width="811" alt="Screenshot 2024-01-04 at 14 38 15" src="https://github.com/statikbe/craft/assets/55497252/1b38907c-58d1-45f0-bbd6-63582cafb903">
@KarelJanVanHaute, @arnaud-dbu, @LauraStatik or @carolineboeykens could you have a look at this?

**Comment by KarelJanVanHaute** [comment]
To fix this, we have to exclude checkboxes from the input_field definition.

**Comment by HannahDeWachter** [comment]
@KarelJanVanHaute Heb jij mijn aanpassingen van op branch [241-optimize-formie-stencil](https://github.com/statikbe/craft/tree/241-optimize-formie-stencil) niet gebruikt?

**Comment by KarelJanVanHaute** [comment]
Ha oei, dat kan misschien van niet. Had niet gezien dat er al een branch aan hing. Je kan hiervoor een nieuwe pull request maken misschien?
