### ISSUE TITLE
SEO - Title homepage other format than other pages

### ISSUE THREAD

**Issue by KarelJanVanHaute** [statikbe/craft#257]
Suggested format: Name Site - Extra optional meta title content
Default format other pages: title page - name website

**Comment by KarelJanVanHaute** [comment]
@janhenckens The title is now generated by the seo-field plugin. Is this something we can change there?

**Comment by KarelJanVanHaute** [comment]
Will be possible to change once this is fixed. https://github.com/studioespresso/craft-seo-fields/issues/90

**Comment by Numkil** [comment]
Closing issue because now possible in plugin
