### ISSUE TITLE
Use responsive images / sourceset for Youtube thumbnails?

### ISSUE THREAD

**Issue by AntonLecock** [statikbe/craft#297]
YouTube generates thumbnail images (freely accessible via URL) for different sizes. We already use the hqdefault but we could go one step further:
* `https://i.ytimg.com/vi/<insert-youtube-video-id-here>/mqdefault.jpg`
* `https://i.ytimg.com/vi/<insert-youtube-video-id-here>/hqdefault.jpg`
* `https://i.ytimg.com/vi/<insert-youtube-video-id-here>/sddefault.jpg`
* `https://i.ytimg.com/vi/<insert-youtube-video-id-here>/maxresdefault.jpg`

Example for video with ID `z5PATyME8tY` ([source](https://www.youtube.com/watch?v=z5PATyME8tY)):
* https://i.ytimg.com/vi/z5PATyME8tY/mqdefault.jpg
* https://i.ytimg.com/vi/z5PATyME8tY/hqdefault.jpg
* https://i.ytimg.com/vi/z5PATyME8tY/sddefault.jpg
* https://i.ytimg.com/vi/z5PATyME8tY/maxresdefault.jpg

**Comment by janhenckens** [comment]
Solid idea! If the user doesn't upload their own placeholder, we could add a sourceset to [this line](https://github.com/statikbe/craft/blob/develop/templates/_site/_snippet/_content/_blocks/_video.twig#L25)
