### ISSUE TITLE
Toegankelijkheidsverklaring toevoegen in footer 

### ISSUE THREAD

**Issue by HannahDeWachter** [statikbe/craft#321]
Kunnen we een link toevoegen in de footer (naast cookie en privacy policy) voor de toegankelijkheidsverklaring?

**Comment by janhenckens** [comment]
Is het een idee om dat ook via een navigatie op te lossen (de hele onderste balk dan)?

**Comment by HannahDeWachter** [comment]
@janhenckens Lijkt me inderdaad wel handig, maar de link naar "Cookie-instellingen" moet wel nog steeds vast in code staan lijkt mij.
