### ISSUE TITLE
Add trigger for lang load in modal component

### ISSUE THREAD

**Issue by LauraStatik** [statikbe/craft#344]
Add following trigger in modal.component.ts :

`private async getLang() {
    this.lang = await import(`../i18n/s-modal-${this.siteLang}.json`);
    if (!this.options.initTriggers) {
      setTimeout(() => {
        window.dispatchEvent(new CustomEvent('modal-loaded'));
      }, 0);
    }
  }`

**Comment by KarelJanVanHaute** [comment]
@LauraStatik weet je nog waarom dit was?

**Comment by LauraStatik** [comment]
We hebben dat in MOBSCH voor de popup van pro articles gebruikt en toen gezien dat dat een trigger was die ook beter algemeen werd ingesteld voor de popup modal. Maar ik kan mij niet meer direct herinneren wat het probleem daarbij was.

**Comment by KarelJanVanHaute** [comment]
Gezien we niet meer goed weten wat dit is, ga ik het voorlopig dicht doen. Als het een probleem is, dan duikt het wel terug op.
