### ISSUE TITLE
[Craft 5] Rename the name fields in Formie Stencil

### ISSUE THREAD

**Issue by HannahDeWachter** [statikbe/craft#355]
We have a Formie Stencil for a NL Contact form. With the Craft 5 upgrade, the Name fields have changed and are in English:
![Screenshot 2024-06-10 at 08 28 43](https://github.com/statikbe/craft/assets/55497252/f655b952-9f80-4aa0-b73f-a4d7a1fa0ee9)

**Comment by SarahOorts** [comment]
Opgelost met https://github.com/statikbe/craft/pull/362
