### ISSUE TITLE
Cookie banner aanpassen op cookie page

### ISSUE THREAD

**Issue by carolineboeykens** [statikbe/craft#36]
Op de plugin:
https://github.com/statikbe/craft-cookie-banner

De modal zou niet moeten openen op de cookies page. Indien we hier een if rond zetten werken de settings op deze pagina niet. Even te bekijken in de plugin.

**Comment by KarelJanVanHaute** [comment]
Er is nu een extra optie showCokkieBanner dat je in _layout.twig kan meegeven om er voor te zorgen dat de cookie banner niet getoond wordt op de cookie policy.

Voorbeeld:
```twig
{# cookiebanner #}
{{ craft.cookieBanner.render({
    supportIE: true,
    showCookieBanner: entry.type.handle != 'cookiePolicy'
}) }}
```

**Comment by carolineboeykens** [comment]
@KarelJanVanHaute , je kan nu je cookie settings niet meer bewerken op de cookies pagina. Zou je hier nog even naar willen kijken? Merci!

**Comment by KarelJanVanHaute** [comment]
Yes nu zou het moeten werken
