### ISSUE TITLE
Remove 'inline' class in _callToActionInclude.twig

### ISSUE THREAD

**Issue by carolineboeykens** [statikbe/craft#81]
The `inline` class on the div in _site/_snippet/_content/_blocks/_callToActionInclude.twig
is not working like it should when you have different buttons next to each other.

We should replace this with a `flex` class above the div:

```
<div class="flex flex-wrap">
  <div class="mt-4 mr-4">
  // button here
  </div>
</div>
```

**Comment by stijnelskens** [comment]
I think `mt-4 mr-4` can be deleted and the `gap` property can be used on the parent div for spacing between links and buttons.

```
<div class="flex flex-wrap gap-4">
  <div>
  // button here
  </div>
</div>
```

**Comment by KarelJanVanHaute** [comment]
This issue is rendered obsolete by the change to hyper see  issue #146
